import Head from "next/head";
import { useState } from "react";

import { Modal } from "@mui/material";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Header from "@/components/Header";
import NavTabs from "@/components/Navtabs";
import Hero from "@/components/Hero";
import Signin from "@/components/form";
import { GetStaticProps } from "next";

type Data = {
  title: string;
  promo: string;
};

interface Props {
  promoText: Data;
}
const Home: React.FC<Props> = ({ promoText }) => {
  const [open, setOpen] = useState(false);

  const handleModalOpen = () => {
    setOpen(true);
  };

  const handleModalClose = () => {
    setOpen(false);
  };

  return (
    <>
      <Head>
        <title>Betway</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Header handleModalOpen={handleModalOpen} />
        <NavTabs />
        <Hero promoText={promoText} />

        <Modal
          open={open}
          onClose={handleModalClose}
          style={{
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
          }}
        >
          <div className={styles.formContainer}>
            <Signin />
          </div>
        </Modal>
      </main>
    </>
  );
};
export const getStaticProps: GetStaticProps = async (context) => {
  //local end point
  const res = await fetch("http://localhost:3000/api");
  const textPromise = res.json();
  const promoText = await textPromise;
  return {
    props: {
      promoText,
    }, // will be passed to the page component as props
  };
};

export default Home;
